=== Greenlamp/Labos3eSup/E-Commerce/Applic_Head_Food/src/xml/exemple.dtd
<!ELEMENT menus (menu*)>
<!ELEMENT menu (nom, vedette, entree+, plat+, dessert+, prix, supplement)>
	<!ELEMENT nom (#PCDATA)>
	<!ELEMENT vedette (#PCDATA)>
	<!ELEMENT prix (#PCDATA)>
	<!ELEMENT supplement (#PCDATA)>

<!ELEMENT entree (nom, chaud?, ingredient+)>
	<!ATTLIST entree id CDATA #REQUIRED>
	<!ELEMENT chaud EMPTY>

<!ELEMENT plat (nom, chaud?, ingredient+)>
	<!ATTLIST plat id CDATA #REQUIRED>

<!ELEMENT dessert (nom, chaud?, ingredient+)>
	<!ATTLIST dessert id CDATA #REQUIRED>

<!ELEMENT ingredient (nom, quantité, alergene?)>
	<!ELEMENT quantité (#PCDATA)>
	<!ELEMENT alergene (#PCDATA)>

=== Greenlamp/Labos3eSup/E-Commerce/Applic_Village_Food/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menus SYSTEM "C:\Users\Greenlamp\Documents\GitHub\Labos3eSup\E-Commerce\Applic_Head_Food\src\xml\exemple.dtd">
<menus>
    <menu>
        <nom>menu1</nom>
        <vedette>kuty</vedette>
        <entree id="1">
            <nom>entree2</nom>
            <ingredient>
                <nom>Fromage à tartiner</nom>
                <quantité>1</quantité>
                <alergene/>
            </ingredient>
        </entree>
        <plat id="1">
            <nom>plat1</nom>
            <chaud/>
            <ingredient>
                <nom>Escalope</nom>
                <quantité>1</quantité>
                <alergene/>
            </ingredient>
        </plat>
        <plat id="2">
            <nom>plat2</nom>
            <chaud/>
            <ingredient>
                <nom>Crème fraîche</nom>
                <quantité>1</quantité>
                <alergene/>
            </ingredient>
        </plat>
        <dessert id="1">
            <nom>dessert1</nom>
            <ingredient>
                <nom>Sucre</nom>
                <quantité>1</quantité>
                <alergene/>
            </ingredient>
            <ingredient>
                <nom>Chocolat noir</nom>
                <quantité>1</quantité>
                <alergene/>
            </ingredient>
        </dessert>
        <dessert id="2">
            <nom>dessert2</nom>
            <ingredient>
                <nom>Beurre</nom>
                <quantité>1</quantité>
                <alergene/>
            </ingredient>
            <ingredient>
                <nom>Sucre roux</nom>
                <quantité>1</quantité>
                <alergene/>
            </ingredient>
        </dessert>
        <prix>0</prix>
        <supplement>0</supplement>
    </menu>
</menus>

=== Greenlamp/Labos3eSup/E-Commerce/Applic_Head_Food/src/xml/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menus SYSTEM "C:\Users\Greenlamp\Documents\GitHub\Labos3eSup\E-Commerce\Applic_Head_Food\src\xml\exemple.dtd">
<menus>
    <menu>
        <nom>a</nom>
        <vedette>a</vedette>
        <entree id="1">
            <nom>a</nom>
            <chaud/>
            <ingredient>
                <nom>Concombre</nom>
                <quantité>1</quantité>
                <alergene/>
            </ingredient>
        </entree>
    </menu>
</menus>

=== Greenlamp/Labos3eSup/E-Commerce/Applic_Head_Food/src/xml/exemple.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menus SYSTEM "C:\Users\Greenlamp\Documents\GitHub\Labos3eSup\E-Commerce\Applic_Head_Food\src\xml\exemple.dtd">
<menus>
	<menu>
		<nom>Délices de Neptune</nom>
		<vedette>Claude Kutty</vedette>

		<entree id="1">
			<nom>De la marée</nom>
			<chaud/>
			<ingredient>
				<nom>gambas</nom>
				<quantité>3</quantité>
				<alergene>sauce aigre-douce</alergene>
			</ingredient>
		</entree>
		<entree id="2">
			<nom>De la marée 2</nom>
			<chaud/>
			<ingredient>
				<nom>gambas</nom>
				<quantité>3</quantité>
				<alergene>sauce aigre-douce</alergene>
			</ingredient>
		</entree>

		<plat id="1">
			<nom>De la marée</nom>
			<chaud/>
			<ingredient>
				<nom>gambas</nom>
				<quantité>3</quantité>
				<alergene>sauce aigre-douce</alergene>
			</ingredient>
		</plat>

		<dessert id="1">
			<nom>De la marée</nom>
			<ingredient>
				<nom>gambas</nom>
				<quantité>3</quantité>
				<alergene>sauce aigre-douce</alergene>
			</ingredient>
		</dessert>

		<prix></prix>
		<supplement>15</supplement>

	</menu>
</menus>
